### ISSUE TITLE
Instance ID & Access token lost when updating

### ISSUE THREAD

**Issue by schrej-zz** [derhansen/tobserver#15]
Hi;
I updated from 9.5.x to 10.4.x and lost Instance ID & Access token in extension configuration.
Is this by purpose? If so, it should be mentioned in the release notes.

**Comment by derhansen** [comment]
No, this is not on purpose. TYPO3 core changes the structure Extension Settings are saved from v9.5 (serialized data) to 10.4 (array data). Although v9.5 supports both formats, TYPO3 users must ensure that extension settings are present in the array configuration (e.g. by updating extension settings for ext:tobserver) before the TYPO3 core update, since the TYPO3 core update will remove serialized extension configuration during the core update.

Note, that this process does not only affect ext:tobserver, but it affects any installed extension in the TYPO3 website, where extension settings are only present in the "old" serialized sturcture.

**Comment by derhansen** [comment]
Closing the issue, since it is most likely not related to the extension
