### ISSUE TITLE
Version display not working (just displays 0.0.0)

### ISSUE THREAD

**Issue by marcelmarty** [derhansen/tobserver#18]
Steps to reproduce:

1. Install TYPO3 12.4 with Composer
2. Install one of the extensions in the image (ig_slug, ke_search or mask)
3. Configure a new tobserver instance on tobserver.com
4. Install the tobserver extension in TYPO3
5. Configure the tobserver extension with its Instance ID and Auth Token
6. Execute the tobserver:update command in the scheduler
7. Check the extensions of the instance on tobserver.com

I just have something like that:
![image](https://github.com/user-attachments/assets/62e56eb3-0c62-47ca-bfd1-12c6e6580ef4)

The extensions which are showed as version "0.0.0" are correctly installed with composer and are working properly

System setup:
- TYPO3 12.4.17
- PHP 8.2.15
- tobserver 3.1.1

**Comment by derhansen** [comment]
Yes, this is a known problem and in general a misconception in tobserver (server). When tobserver was created, composer was not a thing and version numbers usually consited of a string of the schema `major.minor.patch`, which was converted to an integer and saved as integer (for version number comparision reasons). 

Today with composer, version numbers can be different (e.g. `v1.0.0` or `1.0.0-dev` or even `dev-main`) and we have packages for string version number comparisions, so it would be best to change tobserver (server) to save the version number as string. 

The change is however not trivial, since tobserver is in general about version number comparison and several parts of the application would require a refactoring in order to work with version number strings. 

I personally do not use tobserver any more and do not have time or motivation to implement the change or to continue maintenenace of the service. So I'm sorry to say, but the dicision has been taken to shut down the service soon.
